# Generated by Django 4.1.7 on 2023-03-23 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='МЕНЮ')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Пункт меню')),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menuitems', to='one_app.menu')),
                ('otheritem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='one_app.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ПОДМЕНЮ')),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='one_app.menu')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='one_app.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Пункт подменю')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenuitems', to='one_app.menu')),
                ('submenu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submenuitems', to='one_app.submenu')),
            ],
        ),
    ]
