# Generated by Django 4.1.7 on 2023-03-23 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_app', '0003_alter_submenuitem_submenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submenuitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='submenuitem',
            name='submenu',
        ),
        migrations.DeleteModel(
            name='SubMenu',
        ),
        migrations.DeleteModel(
            name='SubMenuItem',
        ),
    ]
